### ISSUE TITLE
Equivalent in KDE

### ISSUE THREAD

**Issue by tim-hilt** [mut-ex/awesome-wm-nice#18]
Sorry to write this in the form of an issue, however this issue can be closed very fast.

Do you know of an equivalent window-decoration in KDE? The closest thing I've found are the [hello](https://github.com/n4n0GH/hello) window-decorations; however they don't have dynamic-adaptation of the titlebar-color.

Otherwise I think I would have to switch to awesome. :smile: :rocket:

**Comment by mut-ex** [comment]
No worries!

Funnily enough, it was hello that inspired me to make nice because I found
something like that lacked for Awesome. Unfortunately that is the only
"similar" window decoration extension I am aware of. I know it lets you
customize the color on a per app basis but it is manual and not dynamic,
like you said. :(

**Comment by tim-hilt** [comment]
Thanks for the quick response! I'll close this for now and come back, if I find something that suits my needs to let you know. :)
